
    
select * from  AI1;
select * from  AI3;
select * from  AI5;
SELECT
    D.DAY_NAME AS DAY,
    GROUP_CONCAT(CASE WHEN S.START_TIME = '08:30' AND S.END_TIME = '10:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '08:30 - 10:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '10:00' AND S.END_TIME = '11:30' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '10:00 - 11:30',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '11:30' AND S.END_TIME = '01:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '11:30 - 01:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '01:30' AND S.END_TIME = '03:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '01:30 - 03:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '03:00' AND S.END_TIME = '04:30' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '03:00 - 04:30'
FROM
    TIMETABLE TT
JOIN CLASS C ON TT.CLASS_ID = C.CLASS_ID
JOIN COURSES CO ON TT.COURSE_ID = CO.CID
JOIN TEACHER T ON TT.TEACHER_ID = T.TID
JOIN ROOM R ON TT.ROOM_ID = R.RID
JOIN DAY D ON TT.DAY_ID = D.DAY_ID
JOIN SLOTS S ON TT.SLOT_ID = S.SID
WHERE
  T.TNAME='DR SALAH UD DIN '
GROUP BY
    D.DAY_NAME
ORDER BY
    FIELD(D.DAY_NAME, 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY');
