CREATE DATABASE IF NOT EXISTS UNI1;
USE UNI1;

-- STEP 2: CREATE TEACHER TABLE
CREATE TABLE IF NOT EXISTS TEACHER (
    TID INT PRIMARY KEY AUTO_INCREMENT,
    TNAME VARCHAR(30) UNIQUE,
    IS_VISITING BOOLEAN
);
CREATE INDEX TEACHER_INDEX ON TEACHER (TID);


-- STEP 3: CREATE DEPARTMENT TABLE
CREATE TABLE IF NOT EXISTS DEP (
    DEPID INT PRIMARY KEY AUTO_INCREMENT,
    DEP_NAME VARCHAR(10)
);
CREATE INDEX DEP_INDEX ON DEP (DEPID);
-- STEP 4: CREATE COURSES TABLE
CREATE TABLE IF NOT EXISTS COURSES (
    CID INT PRIMARY KEY AUTO_INCREMENT,
    CNAME VARCHAR(20) UNIQUE,
    ISLABSUBJECT BOOLEAN
);
CREATE INDEX COURSE_INDEX ON COURSES  (CID);
-- STEP 5: CREATE ROOM TABLE
CREATE TABLE IF NOT EXISTS ROOM (
    RID INT PRIMARY KEY AUTO_INCREMENT,
    RNAME VARCHAR(7),
    DEPID INT,
    FOREIGN KEY (DEPID) REFERENCES DEP(DEPID)
);
create view rooms as select * from ROOM;
CREATE INDEX ROOM_INDEX ON ROOM (RID);

-- STEP 6: CREATE DAY TABLE
CREATE TABLE IF NOT EXISTS DAY (
    DAY_ID INT PRIMARY KEY AUTO_INCREMENT,
    DAY_NAME VARCHAR(10)
);
CREATE INDEX DAY_INDEX ON DAY (DAY_ID);
-- STEP 7: CREATE SLOTS TABLE
CREATE TABLE IF NOT EXISTS SLOTS (
    SID INT PRIMARY KEY AUTO_INCREMENT,
    START_TIME VARCHAR(15),
    END_TIME VARCHAR(15)
);
CREATE INDEX SLOT_ID ON SLOTS (SID,START_TIME,END_TIME);
-- STEP 8: CREATE CLASS TABLE
CREATE TABLE IF NOT EXISTS CLASS (
    CLASS_ID INT PRIMARY KEY AUTO_INCREMENT,
    CNAME VARCHAR(10),
    SEMESTER INT
);
CREATE INDEX class_index ON CLASS (CLASS_ID,CNAME, SEMESTER);

-- STEP 9: CREATE TIMETABLE TABLE
CREATE TABLE IF NOT EXISTS TIMETABLE (
    TIMETABLE_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLASS_ID INT,
    SLOT_ID INT,
    DAY_ID INT,
    ROOM_ID INT,
    TEACHER_ID INT,
    COURSE_ID INT,
    GROUP_NAME ENUM('A', 'B', 'Both') DEFAULT 'Both', -- New column to specify group
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
    FOREIGN KEY (SLOT_ID) REFERENCES SLOTS(SID),
    FOREIGN KEY (DAY_ID) REFERENCES DAY(DAY_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(RID),
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(TID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(CID)
);
create view timetabel as select * from TIMETABEL;
CREATE INDEX TIMETABLE_INDEX ON TIMETABLE (TIMETABLE_ID);
    

CREATE VIEW AI1 AS
SELECT
    D.DAY_NAME AS DAY,
    GROUP_CONCAT(CASE WHEN S.START_TIME = '08:30' AND S.END_TIME = '10:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '08:30 - 10:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '10:00' AND S.END_TIME = '11:30' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '10:00 - 11:30',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '11:30' AND S.END_TIME = '01:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '11:30 - 01:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '01:30' AND S.END_TIME = '03:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '01:30 - 03:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '03:00' AND S.END_TIME = '04:30' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '03:00 - 04:30'
FROM
    TIMETABLE TT
JOIN CLASS C ON TT.CLASS_ID = C.CLASS_ID
JOIN COURSES CO ON TT.COURSE_ID = CO.CID
JOIN TEACHER T ON TT.TEACHER_ID = T.TID
JOIN ROOM R ON TT.ROOM_ID = R.RID
JOIN DAY D ON TT.DAY_ID = D.DAY_ID
JOIN SLOTS S ON TT.SLOT_ID = S.SID
WHERE
    C.CNAME = 'AI' AND C.SEMESTER = 1
GROUP BY
    D.DAY_NAME
ORDER BY
    FIELD(D.DAY_NAME, 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY');





CREATE VIEW AI3 AS SELECT
    D.DAY_NAME AS DAY,
    GROUP_CONCAT(CASE WHEN S.START_TIME = '08:30' AND S.END_TIME = '10:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '08:30 - 10:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '10:00' AND S.END_TIME = '11:30' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '10:00 - 11:30',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '11:30' AND S.END_TIME = '01:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '11:30 - 01:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '01:30' AND S.END_TIME = '03:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '01:30 - 03:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '03:00' AND S.END_TIME = '04:30' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '03:00 - 04:30'
FROM TIMETABLE TT
JOIN CLASS C ON TT.CLASS_ID = C.CLASS_ID
JOIN COURSES CO ON TT.COURSE_ID = CO.CID
JOIN TEACHER T ON TT.TEACHER_ID = T.TID
JOIN ROOM R ON TT.ROOM_ID = R.RID
JOIN DAY D ON TT.DAY_ID = D.DAY_ID
JOIN SLOTS S ON TT.SLOT_ID = S.SID
WHERE
    C.CNAME = 'AI' AND C.SEMESTER = 3
GROUP BY
    D.DAY_NAME
ORDER BY
    FIELD(D.DAY_NAME, 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY');

CREATE VIEW AI5 AS SELECT
    D.DAY_NAME AS DAY,
    GROUP_CONCAT(CASE WHEN S.START_TIME = '08:30' AND S.END_TIME = '10:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '08:30 - 10:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '10:00' AND S.END_TIME = '11:30' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '10:00 - 11:30',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '11:30' AND S.END_TIME = '01:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '11:30 - 01:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '01:30' AND S.END_TIME = '03:00' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '01:30 - 03:00',
    GROUP_CONCAT(CASE WHEN S.START_TIME = '03:00' AND S.END_TIME = '04:30' THEN CONCAT(CO.CNAME, ' - ', T.TNAME, ' - ', R.RNAME, ' - ', TT.GROUP_NAME) END SEPARATOR '') AS '03:00 - 04:30'
FROM TIMETABLE TT
JOIN CLASS C ON TT.CLASS_ID = C.CLASS_ID
JOIN COURSES CO ON TT.COURSE_ID = CO.CID
JOIN TEACHER T ON TT.TEACHER_ID = T.TID
JOIN ROOM R ON TT.ROOM_ID = R.RID
JOIN DAY D ON TT.DAY_ID = D.DAY_ID
JOIN SLOTS S ON TT.SLOT_ID = S.SID
WHERE
    C.CNAME = 'AI' AND C.SEMESTER = 5
GROUP BY
    D.DAY_NAME
ORDER BY
    FIELD(D.DAY_NAME, 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY');
    